name: formula
description: "A new Flutter project."
# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Ensure your SDK version is compatible

# Add these packages under the dependencies section
dependencies:
  flutter:
    sdk: flutter

  # For making HTTP requests (used by web3dart and places_service)
  http: ^1.2.1

  # The core package for interacting with the Ethereum blockchain
  web3dart: ^2.7.2

  # You may also need this if you haven't added it already
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # --- IMPORTANT ---
  # Add this assets section to include your ABI files
  # This tells Flutter to bundle the contents of this folder with your app
  assets:
    - assets/abi/ResearcherAuth.json
    - assets/abi/ManufacturerAuth.json
    - assets/abi/formulanft.json
